"""schema inicial

Revision ID: 2aff3efa097b
Revises: 
Create Date: 2026-07-13 21:00:44.705812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2aff3efa097b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indicador_definicao',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('codigo', sa.String(length=60), nullable=False),
    sa.Column('nome', sa.String(length=160), nullable=False),
    sa.Column('categoria', sa.String(length=60), nullable=True),
    sa.Column('unidade', sa.String(length=40), nullable=True),
    sa.Column('formato', sa.Enum('numero', 'percentual', 'moeda', 'dias', name='formato_indicador'), nullable=False),
    sa.Column('casas_decimais', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('organizacao',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('fazenda',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('municipio', sa.String(length=120), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('area_ha', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizacao.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'nome', name='uq_fazenda_org_nome')
    )
    op.create_index(op.f('ix_fazenda_org_id'), 'fazenda', ['org_id'], unique=False)
    op.create_table('regra_gatilho',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('indicador_id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=160), nullable=False),
    sa.Column('operador', sa.Enum('gt', 'gte', 'lt', 'lte', 'eq', 'ne', 'abs_diff_gt', name='operador'), nullable=False),
    sa.Column('tipo_referencia', sa.Enum('valor_fixo', 'parametro', name='tipo_referencia'), nullable=False),
    sa.Column('valor_referencia', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('parametro_chave', sa.String(length=60), nullable=True),
    sa.Column('tolerancia', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('severidade', sa.Enum('ok', 'revisar', 'avaliar', 'alerta', 'critico', name='severidade'), nullable=False),
    sa.Column('acao', sa.Text(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['indicador_id'], ['indicador_definicao.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizacao.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regra_gatilho_indicador_id'), 'regra_gatilho', ['indicador_id'], unique=False)
    op.create_index(op.f('ix_regra_gatilho_org_id'), 'regra_gatilho', ['org_id'], unique=False)
    op.create_table('usuario',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=180), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('papel', sa.Enum('direcao', 'gerente', 'campo', 'vet', 'admin', name='papel_usuario'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizacao.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_email'), 'usuario', ['email'], unique=True)
    op.create_index(op.f('ix_usuario_org_id'), 'usuario', ['org_id'], unique=False)
    op.create_table('alerta',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fazenda_id', sa.Uuid(), nullable=False),
    sa.Column('regra_id', sa.Uuid(), nullable=False),
    sa.Column('indicador_id', sa.Uuid(), nullable=False),
    sa.Column('severidade', sa.Enum('ok', 'revisar', 'avaliar', 'alerta', 'critico', name='severidade'), nullable=False),
    sa.Column('status', sa.Enum('aberto', 'resolvido', name='status_alerta'), nullable=False),
    sa.Column('valor_observado', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('valor_referencia', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('acao', sa.Text(), nullable=True),
    sa.Column('avaliado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolvido_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fazenda_id'], ['fazenda.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['indicador_id'], ['indicador_definicao.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['regra_id'], ['regra_gatilho.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerta_fazenda_id'), 'alerta', ['fazenda_id'], unique=False)
    op.create_index(op.f('ix_alerta_regra_id'), 'alerta', ['regra_id'], unique=False)
    op.create_table('indicador_valor',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fazenda_id', sa.Uuid(), nullable=False),
    sa.Column('indicador_id', sa.Uuid(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.Column('data_ref', sa.Date(), nullable=False),
    sa.Column('origem', sa.Enum('manual', 'integracao', 'calculo', name='origem_valor'), nullable=False),
    sa.Column('observacao', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fazenda_id'], ['fazenda.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['indicador_id'], ['indicador_definicao.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fazenda_id', 'indicador_id', 'data_ref', name='uq_indicador_valor')
    )
    op.create_index(op.f('ix_indicador_valor_fazenda_id'), 'indicador_valor', ['fazenda_id'], unique=False)
    op.create_index(op.f('ix_indicador_valor_indicador_id'), 'indicador_valor', ['indicador_id'], unique=False)
    op.create_table('parametro',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fazenda_id', sa.Uuid(), nullable=False),
    sa.Column('grupo', sa.String(length=60), nullable=True),
    sa.Column('chave', sa.String(length=60), nullable=False),
    sa.Column('rotulo', sa.String(length=160), nullable=False),
    sa.Column('valor', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.Column('unidade', sa.String(length=40), nullable=True),
    sa.Column('observacao', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fazenda_id'], ['fazenda.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fazenda_id', 'chave', name='uq_parametro_fazenda_chave')
    )
    op.create_index(op.f('ix_parametro_fazenda_id'), 'parametro', ['fazenda_id'], unique=False)
    op.create_table('usuario_fazenda',
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('fazenda_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fazenda_id'], ['fazenda.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id', 'fazenda_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario_fazenda')
    op.drop_index(op.f('ix_parametro_fazenda_id'), table_name='parametro')
    op.drop_table('parametro')
    op.drop_index(op.f('ix_indicador_valor_indicador_id'), table_name='indicador_valor')
    op.drop_index(op.f('ix_indicador_valor_fazenda_id'), table_name='indicador_valor')
    op.drop_table('indicador_valor')
    op.drop_index(op.f('ix_alerta_regra_id'), table_name='alerta')
    op.drop_index(op.f('ix_alerta_fazenda_id'), table_name='alerta')
    op.drop_table('alerta')
    op.drop_index(op.f('ix_usuario_org_id'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_email'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_regra_gatilho_org_id'), table_name='regra_gatilho')
    op.drop_index(op.f('ix_regra_gatilho_indicador_id'), table_name='regra_gatilho')
    op.drop_table('regra_gatilho')
    op.drop_index(op.f('ix_fazenda_org_id'), table_name='fazenda')
    op.drop_table('fazenda')
    op.drop_table('organizacao')
    op.drop_table('indicador_definicao')
    # ### end Alembic commands ###
