"""reproducao: inseminacao

Revision ID: 384ffa2bfc5e
Revises: 71c5afa73441
Create Date: 2026-07-14 17:18:02.231735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '384ffa2bfc5e'
down_revision: Union[str, None] = '71c5afa73441'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inseminacao',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fazenda_id', sa.Uuid(), nullable=False),
    sa.Column('animal_id', sa.Uuid(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('touro', sa.String(length=120), nullable=False),
    sa.Column('inseminador', sa.String(length=120), nullable=True),
    sa.Column('protocolo', sa.String(length=120), nullable=True),
    sa.Column('resultado', sa.String(length=12), nullable=False),
    sa.Column('dg_data', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fazenda_id'], ['fazenda.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inseminacao_animal_id'), 'inseminacao', ['animal_id'], unique=False)
    op.create_index(op.f('ix_inseminacao_fazenda_id'), 'inseminacao', ['fazenda_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inseminacao_fazenda_id'), table_name='inseminacao')
    op.drop_index(op.f('ix_inseminacao_animal_id'), table_name='inseminacao')
    op.drop_table('inseminacao')
    # ### end Alembic commands ###
