"""estoque volumoso + dieta

Revision ID: 43963d9c731c
Revises: 384ffa2bfc5e
Create Date: 2026-07-14 17:40:55.977627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43963d9c731c'
down_revision: Union[str, None] = '384ffa2bfc5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movimento_volumoso',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fazenda_id', sa.Uuid(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('quantidade_t', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('descricao', sa.String(length=160), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fazenda_id'], ['fazenda.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimento_volumoso_fazenda_id'), 'movimento_volumoso', ['fazenda_id'], unique=False)
    op.create_table('dieta',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fazenda_id', sa.Uuid(), nullable=False),
    sa.Column('lote_id', sa.Uuid(), nullable=True),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fazenda_id'], ['fazenda.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lote_id'], ['lote.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dieta_fazenda_id'), 'dieta', ['fazenda_id'], unique=False)
    op.create_index(op.f('ix_dieta_lote_id'), 'dieta', ['lote_id'], unique=False)
    op.create_table('item_dieta',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dieta_id', sa.Uuid(), nullable=False),
    sa.Column('ingrediente', sa.String(length=120), nullable=False),
    sa.Column('inclusao_kg', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('preco_kg', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('ms_pct', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dieta_id'], ['dieta.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_dieta_dieta_id'), 'item_dieta', ['dieta_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_dieta_dieta_id'), table_name='item_dieta')
    op.drop_table('item_dieta')
    op.drop_index(op.f('ix_dieta_lote_id'), table_name='dieta')
    op.drop_index(op.f('ix_dieta_fazenda_id'), table_name='dieta')
    op.drop_table('dieta')
    op.drop_index(op.f('ix_movimento_volumoso_fazenda_id'), table_name='movimento_volumoso')
    op.drop_table('movimento_volumoso')
    # ### end Alembic commands ###
