"""rebanho: lote, animal, pesagem

Revision ID: 71c5afa73441
Revises: 2aff3efa097b
Create Date: 2026-07-13 22:00:49.311949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71c5afa73441'
down_revision: Union[str, None] = '2aff3efa097b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lote',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fazenda_id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('categoria', sa.String(length=40), nullable=True),
    sa.Column('local', sa.String(length=80), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fazenda_id'], ['fazenda.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lote_fazenda_id'), 'lote', ['fazenda_id'], unique=False)
    op.create_table('animal',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fazenda_id', sa.Uuid(), nullable=False),
    sa.Column('lote_id', sa.Uuid(), nullable=True),
    sa.Column('brinco', sa.String(length=40), nullable=False),
    sa.Column('categoria', sa.String(length=40), nullable=True),
    sa.Column('raca', sa.String(length=60), nullable=True),
    sa.Column('sexo', sa.String(length=1), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('mae_brinco', sa.String(length=40), nullable=True),
    sa.Column('pai', sa.String(length=80), nullable=True),
    sa.Column('origem', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fazenda_id'], ['fazenda.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lote_id'], ['lote.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fazenda_id', 'brinco', name='uq_animal_fazenda_brinco')
    )
    op.create_index(op.f('ix_animal_fazenda_id'), 'animal', ['fazenda_id'], unique=False)
    op.create_index(op.f('ix_animal_lote_id'), 'animal', ['lote_id'], unique=False)
    op.create_table('pesagem',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fazenda_id', sa.Uuid(), nullable=False),
    sa.Column('animal_id', sa.Uuid(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('peso', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('gmd', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('observacao', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fazenda_id'], ['fazenda.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pesagem_animal_id'), 'pesagem', ['animal_id'], unique=False)
    op.create_index(op.f('ix_pesagem_fazenda_id'), 'pesagem', ['fazenda_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pesagem_fazenda_id'), table_name='pesagem')
    op.drop_index(op.f('ix_pesagem_animal_id'), table_name='pesagem')
    op.drop_table('pesagem')
    op.drop_index(op.f('ix_animal_lote_id'), table_name='animal')
    op.drop_index(op.f('ix_animal_fazenda_id'), table_name='animal')
    op.drop_table('animal')
    op.drop_index(op.f('ix_lote_fazenda_id'), table_name='lote')
    op.drop_table('lote')
    # ### end Alembic commands ###
