"""mercado: cotacao arroba e insumo

Revision ID: 891a8da4ad98
Revises: 43963d9c731c
Create Date: 2026-07-14 18:02:16.674024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '891a8da4ad98'
down_revision: Union[str, None] = '43963d9c731c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cotacao_arroba',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fazenda_id', sa.Uuid(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('origem', sa.String(length=20), nullable=False),
    sa.Column('fonte', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fazenda_id'], ['fazenda.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cotacao_arroba_fazenda_id'), 'cotacao_arroba', ['fazenda_id'], unique=False)
    op.create_table('cotacao_insumo',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fazenda_id', sa.Uuid(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('insumo', sa.String(length=120), nullable=False),
    sa.Column('praca', sa.String(length=120), nullable=True),
    sa.Column('unidade', sa.String(length=10), nullable=False),
    sa.Column('preco_origem', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('frete', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('outros', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('ms_pct', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fazenda_id'], ['fazenda.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cotacao_insumo_fazenda_id'), 'cotacao_insumo', ['fazenda_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cotacao_insumo_fazenda_id'), table_name='cotacao_insumo')
    op.drop_table('cotacao_insumo')
    op.drop_index(op.f('ix_cotacao_arroba_fazenda_id'), table_name='cotacao_arroba')
    op.drop_table('cotacao_arroba')
    # ### end Alembic commands ###
