"""sanitario + movimento animal

Revision ID: d65e08c46ffb
Revises: 891a8da4ad98
Create Date: 2026-07-15 20:23:04.456619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd65e08c46ffb'
down_revision: Union[str, None] = '891a8da4ad98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evento_sanitario',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fazenda_id', sa.Uuid(), nullable=False),
    sa.Column('animal_id', sa.Uuid(), nullable=False),
    sa.Column('lote_id', sa.Uuid(), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('produto', sa.String(length=120), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('proxima_aplicacao', sa.Date(), nullable=True),
    sa.Column('dose', sa.String(length=40), nullable=True),
    sa.Column('observacao', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fazenda_id'], ['fazenda.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lote_id'], ['lote.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evento_sanitario_animal_id'), 'evento_sanitario', ['animal_id'], unique=False)
    op.create_index(op.f('ix_evento_sanitario_fazenda_id'), 'evento_sanitario', ['fazenda_id'], unique=False)
    op.create_index(op.f('ix_evento_sanitario_proxima_aplicacao'), 'evento_sanitario', ['proxima_aplicacao'], unique=False)
    op.create_table('movimento_animal',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fazenda_id', sa.Uuid(), nullable=False),
    sa.Column('animal_id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('motivo', sa.String(length=120), nullable=True),
    sa.Column('lote_destino_id', sa.Uuid(), nullable=True),
    sa.Column('observacao', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fazenda_id'], ['fazenda.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lote_destino_id'], ['lote.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimento_animal_animal_id'), 'movimento_animal', ['animal_id'], unique=False)
    op.create_index(op.f('ix_movimento_animal_data'), 'movimento_animal', ['data'], unique=False)
    op.create_index(op.f('ix_movimento_animal_fazenda_id'), 'movimento_animal', ['fazenda_id'], unique=False)
    op.create_index(op.f('ix_movimento_animal_tipo'), 'movimento_animal', ['tipo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movimento_animal_tipo'), table_name='movimento_animal')
    op.drop_index(op.f('ix_movimento_animal_fazenda_id'), table_name='movimento_animal')
    op.drop_index(op.f('ix_movimento_animal_data'), table_name='movimento_animal')
    op.drop_index(op.f('ix_movimento_animal_animal_id'), table_name='movimento_animal')
    op.drop_table('movimento_animal')
    op.drop_index(op.f('ix_evento_sanitario_proxima_aplicacao'), table_name='evento_sanitario')
    op.drop_index(op.f('ix_evento_sanitario_fazenda_id'), table_name='evento_sanitario')
    op.drop_index(op.f('ix_evento_sanitario_animal_id'), table_name='evento_sanitario')
    op.drop_table('evento_sanitario')
    # ### end Alembic commands ###
